spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nilanchala2001/config-repo.git
          username: Nilanchala2001
          password: Nilanchala@977
          default-label: main
          clone-on-start: true
